import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import ButtonAddImage from "../components/ButtonAddImage";
import ShowGalley from "../components/ShowGalley";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Made My Pizza !!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="my-5">  
        <ButtonAddImage/>
        <br/>
        <ShowGalley/>
      </div>
    </div>
  );
}
